### ISSUE TITLE
Flak Cannon bug

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#1327]
Fatal error: Uncaught Error: Call to a member function getAllFireOrders() on null in /var/www/html/source/server/model/weapons/matter.php:532 Stack trace: #0 /var/www/html/source/server/handlers/firing.php(472): FlakCannon->calculateHitBase(Object(TacGamedata), Object(FireOrder)) #1 /var/www/html/source/server/Phase/FireGamePhase.php(15): Firing::prepareFiring(Object(TacGamedata)) #2 /var/www/html/source/server/controller/Manager.php(472): FireGamePhase->advance(Object(TacGamedata), Object(DBManager)) #3 /var/www/html/source/server/controller/Manager.php(269): Manager::advanceGameState(-1, '6634') #4 /var/www/html/source/public/game.php(18): Manager::getTacGamedata('6634', -1, NULL, 0, -1) #5 {main} thrown in /var/www/html/source/server/model/weapons/matter.php on line 532

description:
We have Grome flak cannons as well as firing mass drivers.
Speaking to @mwaschak, only the Grome bases fired. They only fired the heavy railguns and did not use any special shells. So, it appears the main problem may be the flak cannons and mass drivers interacting.

**Comment by Zero1627** [comment]
reason: mode change changed hextarget attribute for other arrays as well, causing weapon to become hextargeted instead of switching non-interceptability (copy-paste bug).

Corrected.

**Comment by Zero1627** [comment]
works!
